// Default: 1.20.1 with Java 17
// For 1.19.2 (optional): ./gradlew build -DMC_VERSION=1.19.2 -DMAPPING_VERSION=1.19.2 -DFORGE_VERSION=1.19.2-43.X.X
def mc_version = project.findProperty('MC_VERSION') ?: System.getProperty('MC_VERSION') ?: '1.20.1'
def compileModsDirBase = mc_version.startsWith('1.19') ? 'compile-mods-1.19.2' : 'compile-mods-1.20.1'

println("mcreator.gradle: Using compile-mods for version ${mc_version}")

def compileModsDir = compileModsDirBase
	task addnewfoldersmods(type: DefaultTask){
		ant.mkdir(dir: "${compileModsDir}/");
    }
    repositories {
    	flatDir {
    	name "compile-mods" 
    	dir file(compileModsDir)
    	}
    }
          
    dependencies {
    	for (compileModJar in fileTree(dir: compileModsDir, include: '*.jar')) {
    	def basename = compileModJar.name.substring(0, compileModJar.name.length() - ".jar".length()) 
    	def versionSep = basename.lastIndexOf('-') 
    	assert versionSep != -1 
    	def artifactId = basename.substring(0, versionSep) 
    	def version = basename.substring(versionSep + 1)
    	implementation fg.deobf("compile-mods:$artifactId:$version")}
    }

repositories {
maven {
	url = "https://maven.theillusivec4.top/"
	}
}

dependencies {
	if (mc_version.startsWith('1.19')) {
		runtimeOnly fg.deobf("top.theillusivec4.curios:curios-forge:1.19.2-5.1.1.0")
		compileOnly fg.deobf("top.theillusivec4.curios:curios-forge:1.19.2-5.1.1.0:api")
	} else if (mc_version.startsWith('1.20')) {
		// Note: For 1.20.1, use deobf to get source variants
		runtimeOnly fg.deobf("top.theillusivec4.curios:curios-forge:1.20.1-5.3.7.0:deobf")
		compileOnly fg.deobf("top.theillusivec4.curios:curios-forge:1.20.1-5.3.7.0:deobf@jar")
	}
}

repositories {
  maven {
      url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
  }
}

dependencies {
	if (mc_version.startsWith('1.19')) {
		implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.19:3.1.40')
	} else if (mc_version.startsWith('1.20')) {
		// GeckoLib 4.x for 1.20.1
		implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.20:4.4.7')
	}
}

repositories {
  maven {
    // location of the maven that hosts JEI files
    name = "Progwml6 maven"
    url = "https://dvs1.progwml6.com/files/maven/"
  }    
  maven {
    // location of a maven mirror for JEI files, as a fallback
    name = "ModMaven"
    url = "https://modmaven.dev"
  }   
}

dependencies {
	if (mc_version.startsWith('1.19')) {
		compileOnly fg.deobf("mezz.jei:jei-1.19.2-common-api:11.4.0.286")
		compileOnly fg.deobf("mezz.jei:jei-1.19.2-forge-api:11.4.0.286")
		runtimeOnly fg.deobf("mezz.jei:jei-1.19.2-forge:11.4.0.286")
	} else if (mc_version.startsWith('1.20')) {
		// JEI 15.x for 1.20.1
		compileOnly fg.deobf("mezz.jei:jei-1.20.1-common-api:14.6.13.56")
		compileOnly fg.deobf("mezz.jei:jei-1.20.1-forge-api:14.6.13.56")
		runtimeOnly fg.deobf("mezz.jei:jei-1.20.1-forge:14.6.13.56")
	}
}

