modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="the_four_primitives_and_weapons"
version="1.0.0"
displayName="The-four-primitives-and-Weapons"
credits="nemui"
displayURL="https://curseforge.com/minecraft/mc-mods/the-four-primitives-and-weapons"
updateJSONURL="https://curseforge.com/minecraft/mc-mods/the-four-primitives-and-weapons/files/all?page=1&pageSize=20"
logoFile="logo.png"
authors="reisame"

[[dependencies.the_four_primitives_and_weapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"



[[dependencies.the_four_primitives_and_weapons]]
    modId="use_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.the_four_primitives_and_weapons]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.the_four_primitives_and_weapons]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.the_four_primitives_and_weapons]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

