
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package the_four_primitives_and_weapons.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.effect.MobEffect;

import the_four_primitives_and_weapons.potion.ZokuseizanngekiMobEffect;
import the_four_primitives_and_weapons.potion.ZanngekitokubetuMobEffect;
import the_four_primitives_and_weapons.potion.ZanngekikaiMobEffect;
import the_four_primitives_and_weapons.potion.YouwakaranMobEffect;
import the_four_primitives_and_weapons.potion.WindStepEffectMobEffect;
import the_four_primitives_and_weapons.potion.WazaMobEffect;
import the_four_primitives_and_weapons.potion.TunderbolteffrctMobEffect;
import the_four_primitives_and_weapons.potion.TpAttackMobEffect;
import the_four_primitives_and_weapons.potion.TokubetusounazangekiMobEffect;
import the_four_primitives_and_weapons.potion.TokubetuMobEffect;
import the_four_primitives_and_weapons.potion.TobeMobEffect;
import the_four_primitives_and_weapons.potion.TissokuMobEffect;
import the_four_primitives_and_weapons.potion.ThunderHitMobEffect;
import the_four_primitives_and_weapons.potion.TestMobEffect;
import the_four_primitives_and_weapons.potion.SyugekinanozeeMobEffect;
import the_four_primitives_and_weapons.potion.SyugekiMobEffect;
import the_four_primitives_and_weapons.potion.SwordOfNightTameeeeMobEffect;
import the_four_primitives_and_weapons.potion.SwordOfNightReloadMobEffect;
import the_four_primitives_and_weapons.potion.SwordOfNightEffectMobEffect;
import the_four_primitives_and_weapons.potion.SummonTriggerEffectMobEffect;
import the_four_primitives_and_weapons.potion.SuityuuMobEffect;
import the_four_primitives_and_weapons.potion.StormEffectMobEffect;
import the_four_primitives_and_weapons.potion.SliceGuardMobEffect;
import the_four_primitives_and_weapons.potion.PlayerScoreIdMobEffect;
import the_four_primitives_and_weapons.potion.OtitaMobEffect;
import the_four_primitives_and_weapons.potion.OtiruyooMobEffect;
import the_four_primitives_and_weapons.potion.OtiroMobEffect;
import the_four_primitives_and_weapons.potion.OnazitakasaArrowMobEffect;
import the_four_primitives_and_weapons.potion.NgsMobEffect;
import the_four_primitives_and_weapons.potion.LongRangeWeaponCutMobEffect;
import the_four_primitives_and_weapons.potion.KurutimenasiMobEffect;
import the_four_primitives_and_weapons.potion.KougekiMobEffect;
import the_four_primitives_and_weapons.potion.KitterukitteruMobEffect;
import the_four_primitives_and_weapons.potion.KilloffMobEffect;
import the_four_primitives_and_weapons.potion.KillEffectTrueOrFalseMobEffect;
import the_four_primitives_and_weapons.potion.KarikarisiterunemaidomaidoMobEffect;
import the_four_primitives_and_weapons.potion.KaminariyadeMobEffect;
import the_four_primitives_and_weapons.potion.KaitenMobEffect;
import the_four_primitives_and_weapons.potion.HardentityMobEffect;
import the_four_primitives_and_weapons.potion.GyetonzangekiMobEffect;
import the_four_primitives_and_weapons.potion.GuwaazangekiMobEffect;
import the_four_primitives_and_weapons.potion.GuardMobEffect;
import the_four_primitives_and_weapons.potion.FireballeffectMobEffect;
import the_four_primitives_and_weapons.potion.EnmazangekiMobEffect;
import the_four_primitives_and_weapons.potion.EffectMagicMobEffect;
import the_four_primitives_and_weapons.potion.EffectBloodTpMobEffect;
import the_four_primitives_and_weapons.potion.DevourBloodMobEffect;
import the_four_primitives_and_weapons.potion.DarknessAttackEffectMobEffect;
import the_four_primitives_and_weapons.potion.CustomsmithingtablecraftingMobEffect;
import the_four_primitives_and_weapons.potion.ChuzumeHuskArmorKnockBackMobEffect;
import the_four_primitives_and_weapons.potion.BubbleshotEffectMobEffect;
import the_four_primitives_and_weapons.potion.BowAttackMobEffect;
import the_four_primitives_and_weapons.potion.BloodTpMobEffect;
import the_four_primitives_and_weapons.potion.BlackHoleEffectMobEffect;
import the_four_primitives_and_weapons.potion.BarrierEffectMobEffect;
import the_four_primitives_and_weapons.potion.BakuhatuMobEffect;
import the_four_primitives_and_weapons.potion.AttackInGuardMobEffect;
import the_four_primitives_and_weapons.potion.AttackBowMobEffect;
import the_four_primitives_and_weapons.potion.Arrow1MobEffect;
import the_four_primitives_and_weapons.potion.ArmorstandtobasuenmaeffectkillMobEffect;
import the_four_primitives_and_weapons.potion.ArmorstandtobasueffectkillMobEffect;
import the_four_primitives_and_weapons.potion.ArmorStandTobasuEffectMobEffect;
import the_four_primitives_and_weapons.potion.AlchemyCraftBlockEffectMobEffect;
import the_four_primitives_and_weapons.potion.AaaaMobEffect;
import the_four_primitives_and_weapons.potion.AaMobEffect;

import the_four_primitives_and_weapons.TheFourPrimitivesAndWeaponsMod;

public class TheFourPrimitivesAndWeaponsModMobEffects {
	public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(ForgeRegistries.MOB_EFFECTS, TheFourPrimitivesAndWeaponsMod.MODID);
	public static final RegistryObject<MobEffect> FIREBALLEFFECT = REGISTRY.register("fireballeffect", () -> new FireballeffectMobEffect());
	public static final RegistryObject<MobEffect> ARROW_1 = REGISTRY.register("arrow_1", () -> new Arrow1MobEffect());
	public static final RegistryObject<MobEffect> TUNDERBOLTEFFRCT = REGISTRY.register("tunderbolteffrct", () -> new TunderbolteffrctMobEffect());
	public static final RegistryObject<MobEffect> BOW_ATTACK = REGISTRY.register("bow_attack", () -> new BowAttackMobEffect());
	public static final RegistryObject<MobEffect> ATTACK_BOW = REGISTRY.register("attack_bow", () -> new AttackBowMobEffect());
	public static final RegistryObject<MobEffect> OTIRUYOO = REGISTRY.register("otiruyoo", () -> new OtiruyooMobEffect());
	public static final RegistryObject<MobEffect> AAAA = REGISTRY.register("aaaa", () -> new AaaaMobEffect());
	public static final RegistryObject<MobEffect> SYUGEKI = REGISTRY.register("syugeki", () -> new SyugekiMobEffect());
	public static final RegistryObject<MobEffect> SUITYUU = REGISTRY.register("suityuu", () -> new SuityuuMobEffect());
	public static final RegistryObject<MobEffect> TISSOKU = REGISTRY.register("tissoku", () -> new TissokuMobEffect());
	public static final RegistryObject<MobEffect> BUBBLESHOT_EFFECT = REGISTRY.register("bubbleshot_effect", () -> new BubbleshotEffectMobEffect());
	public static final RegistryObject<MobEffect> THUNDER_HIT = REGISTRY.register("thunder_hit", () -> new ThunderHitMobEffect());
	public static final RegistryObject<MobEffect> KURUTIMENASI = REGISTRY.register("kurutimenasi", () -> new KurutimenasiMobEffect());
	public static final RegistryObject<MobEffect> WAZA = REGISTRY.register("waza", () -> new WazaMobEffect());
	public static final RegistryObject<MobEffect> EFFECT_MAGIC = REGISTRY.register("effect_magic", () -> new EffectMagicMobEffect());
	public static final RegistryObject<MobEffect> BARRIER_EFFECT = REGISTRY.register("barrier_effect", () -> new BarrierEffectMobEffect());
	public static final RegistryObject<MobEffect> AA = REGISTRY.register("aa", () -> new AaMobEffect());
	public static final RegistryObject<MobEffect> OTIRO = REGISTRY.register("otiro", () -> new OtiroMobEffect());
	public static final RegistryObject<MobEffect> WIND_STEP_EFFECT = REGISTRY.register("wind_step_effect", () -> new WindStepEffectMobEffect());
	public static final RegistryObject<MobEffect> KAITEN = REGISTRY.register("kaiten", () -> new KaitenMobEffect());
	public static final RegistryObject<MobEffect> OTITA = REGISTRY.register("otita", () -> new OtitaMobEffect());
	public static final RegistryObject<MobEffect> ZANNGEKITOKUBETU = REGISTRY.register("zanngekitokubetu", () -> new ZanngekitokubetuMobEffect());
	public static final RegistryObject<MobEffect> YOUWAKARAN = REGISTRY.register("youwakaran", () -> new YouwakaranMobEffect());
	public static final RegistryObject<MobEffect> GYETONZANGEKI = REGISTRY.register("gyetonzangeki", () -> new GyetonzangekiMobEffect());
	public static final RegistryObject<MobEffect> TOBE = REGISTRY.register("tobe", () -> new TobeMobEffect());
	public static final RegistryObject<MobEffect> KOUGEKI = REGISTRY.register("kougeki", () -> new KougekiMobEffect());
	public static final RegistryObject<MobEffect> ZANNGEKIKAI = REGISTRY.register("zanngekikai", () -> new ZanngekikaiMobEffect());
	public static final RegistryObject<MobEffect> SYUGEKINANOZEE = REGISTRY.register("syugekinanozee", () -> new SyugekinanozeeMobEffect());
	public static final RegistryObject<MobEffect> KAMINARIYADE = REGISTRY.register("kaminariyade", () -> new KaminariyadeMobEffect());
	public static final RegistryObject<MobEffect> TOKUBETUSOUNAZANGEKI = REGISTRY.register("tokubetusounazangeki", () -> new TokubetusounazangekiMobEffect());
	public static final RegistryObject<MobEffect> KARIKARISITERUNEMAIDOMAIDO = REGISTRY.register("karikarisiterunemaidomaido", () -> new KarikarisiterunemaidomaidoMobEffect());
	public static final RegistryObject<MobEffect> DEVOUR_BLOOD = REGISTRY.register("devour_blood", () -> new DevourBloodMobEffect());
	public static final RegistryObject<MobEffect> EFFECT_BLOOD_TP = REGISTRY.register("effect_blood_tp", () -> new EffectBloodTpMobEffect());
	public static final RegistryObject<MobEffect> BLOOD_TP = REGISTRY.register("blood_tp", () -> new BloodTpMobEffect());
	public static final RegistryObject<MobEffect> NGS = REGISTRY.register("ngs", () -> new NgsMobEffect());
	public static final RegistryObject<MobEffect> SWORD_OF_NIGHT_EFFECT = REGISTRY.register("sword_of_night_effect", () -> new SwordOfNightEffectMobEffect());
	public static final RegistryObject<MobEffect> LONG_RANGE_WEAPON_CUT = REGISTRY.register("long_range_weapon_cut", () -> new LongRangeWeaponCutMobEffect());
	public static final RegistryObject<MobEffect> STORM_EFFECT = REGISTRY.register("storm_effect", () -> new StormEffectMobEffect());
	public static final RegistryObject<MobEffect> KITTERUKITTERU = REGISTRY.register("kitterukitteru", () -> new KitterukitteruMobEffect());
	public static final RegistryObject<MobEffect> TP_ATTACK = REGISTRY.register("tp_attack", () -> new TpAttackMobEffect());
	public static final RegistryObject<MobEffect> ZOKUSEIZANNGEKI = REGISTRY.register("zokuseizanngeki", () -> new ZokuseizanngekiMobEffect());
	public static final RegistryObject<MobEffect> SWORD_OF_NIGHT_RELOAD = REGISTRY.register("sword_of_night_reload", () -> new SwordOfNightReloadMobEffect());
	public static final RegistryObject<MobEffect> SWORD_OF_NIGHT_TAMEEEE = REGISTRY.register("sword_of_night_tameeee", () -> new SwordOfNightTameeeeMobEffect());
	public static final RegistryObject<MobEffect> TEST = REGISTRY.register("test", () -> new TestMobEffect());
	public static final RegistryObject<MobEffect> GUARD = REGISTRY.register("guard", () -> new GuardMobEffect());
	public static final RegistryObject<MobEffect> BLACK_HOLE_EFFECT = REGISTRY.register("black_hole_effect", () -> new BlackHoleEffectMobEffect());
	public static final RegistryObject<MobEffect> DARKNESS_ATTACK_EFFECT = REGISTRY.register("darkness_attack_effect", () -> new DarknessAttackEffectMobEffect());
	public static final RegistryObject<MobEffect> TOKUBETU = REGISTRY.register("tokubetu", () -> new TokubetuMobEffect());
	public static final RegistryObject<MobEffect> ATTACK_IN_GUARD = REGISTRY.register("attack_in_guard", () -> new AttackInGuardMobEffect());
	public static final RegistryObject<MobEffect> CHUZUME_HUSK_ARMOR_KNOCK_BACK = REGISTRY.register("chuzume_husk_armor_knock_back", () -> new ChuzumeHuskArmorKnockBackMobEffect());
	public static final RegistryObject<MobEffect> HARDENTITY = REGISTRY.register("hardentity", () -> new HardentityMobEffect());
	public static final RegistryObject<MobEffect> CUSTOMSMITHINGTABLECRAFTING = REGISTRY.register("customsmithingtablecrafting", () -> new CustomsmithingtablecraftingMobEffect());
	public static final RegistryObject<MobEffect> ARMOR_STAND_TOBASU_EFFECT = REGISTRY.register("armor_stand_tobasu_effect", () -> new ArmorStandTobasuEffectMobEffect());
	public static final RegistryObject<MobEffect> ARMORSTANDTOBASUEFFECTKILL = REGISTRY.register("armorstandtobasueffectkill", () -> new ArmorstandtobasueffectkillMobEffect());
	public static final RegistryObject<MobEffect> PLAYER_SCORE_ID = REGISTRY.register("player_score_id", () -> new PlayerScoreIdMobEffect());
	public static final RegistryObject<MobEffect> KILL_EFFECT_TRUE_OR_FALSE = REGISTRY.register("kill_effect_true_or_false", () -> new KillEffectTrueOrFalseMobEffect());
	public static final RegistryObject<MobEffect> ONAZITAKASA_ARROW = REGISTRY.register("onazitakasa_arrow", () -> new OnazitakasaArrowMobEffect());
	public static final RegistryObject<MobEffect> BAKUHATU = REGISTRY.register("bakuhatu", () -> new BakuhatuMobEffect());
	public static final RegistryObject<MobEffect> ALCHEMY_CRAFT_BLOCK_EFFECT = REGISTRY.register("alchemy_craft_block_effect", () -> new AlchemyCraftBlockEffectMobEffect());
	public static final RegistryObject<MobEffect> SLICE_GUARD = REGISTRY.register("slice_guard", () -> new SliceGuardMobEffect());
	public static final RegistryObject<MobEffect> GUWAAZANGEKI = REGISTRY.register("guwaazangeki", () -> new GuwaazangekiMobEffect());
	public static final RegistryObject<MobEffect> ARMORSTANDTOBASUENMAEFFECTKILL = REGISTRY.register("armorstandtobasuenmaeffectkill", () -> new ArmorstandtobasuenmaeffectkillMobEffect());
	public static final RegistryObject<MobEffect> KILLOFF = REGISTRY.register("killoff", () -> new KilloffMobEffect());
	public static final RegistryObject<MobEffect> ENMAZANGEKI = REGISTRY.register("enmazangeki", () -> new EnmazangekiMobEffect());
	public static final RegistryObject<MobEffect> SUMMON_TRIGGER_EFFECT = REGISTRY.register("summon_trigger_effect", () -> new SummonTriggerEffectMobEffect());
}
