name: Epic Java CI Adventure with Gradle

on:
  push:
    branches: [ "1.19.2" ]
  pull_request:
    branches: [ "1.19.2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: 🏁 Checkout the Codebase
      uses: actions/checkout@v4

    - name: ☕ Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 🛠️ Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

    - name: 🔧 Grant Execute Permission for Gradlew
      run: chmod +x ./gradlew

    - name: 🚀 Let the Adventure Begin! Starting the Build...
      run: echo "🚀 Let the adventure begin! Starting the build process..."

    - name: ⚒️ Build the Fortress with Gradle Wrapper
      run: ./gradlew build -x test -Dorg.gradle.daemon=false

    - name: 🏗️ Building the Fortress, Please Wait...
      run: echo "🏗️ Building the fortress, please wait..."

    - name: 🎉 The Build is Complete! Your Code is Now Battle-Ready!
      run: echo "🎉 The build is complete! Your code is now battle-ready!"

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 🏁 Checkout the Codebase
      uses: actions/checkout@v4

    - name: ☕ Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 📊 Generate and Submit Dependency Graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5
